First Capstone Project
anyars-encarta/First-Capstone pull request #1
Opened 2023-07-05 19:25 UTC by anyars-encarta

In this project, 

- [ ] I developed a two-page website.
- [ ] The website includes a home page and an About page.
- [ ] The About button on the Home page opens the About page.
- [ ] The logo on the About page opens the Home page.
- [ ] Both pages are response for both mobile and desktop views.
- [ ] While on the mobile view, a hamburger icon opens the menu.
- [ ] Tapping on About on the mobile menu opens the About mobile view.
- [ ] The mobile Home page features a list of 2 speakers with a MORE button beneath.
- [ ] Clicking the MORE button expands to show the remaining speakers.
- [ ] Clicking LESS button below collapses the speakers again to show only two speakers.
- [ ] The speakers data are created dynamically with JavaScript when the page loads.

- [ ] I used HTML, CSS and JavaScript

2023-07-05 21:37 UTC, Felix45 requested changes
Hi @anyars-encarta, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="300px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Speakers section is generated dynamically using JavaScript
- [x] Student implemented the `See more` speakers functionality using JavaScript
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:     


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 21:37 UTC, Felix45 commented on README.md
- [ Required ] I think it would be better if the author of this design, Cindy Shin, is also mentioned in the attribution. Currently, only the website where the design is hosted is mentioned. I would like to suggest that you change the attribution to something like the one below. 

Special credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) on [behance.net](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) used in this project.

2023-07-05 21:37 UTC, Felix45 commented on about.html
> +                        <li class="bottom-nav-item"><a href="./about.html" class="bottom-nav-link">About</a></li>
- [ Required ] I think it would be better if you provide a link to the `homepage` on the `About` page to make it easy for a user to navigate back to the homepage. I would like to suggest that you change the `About` menu on the About page to `Home` and link to the `index.html` file.

2023-07-05 21:37 UTC, Felix45 commented on index.html
> +        </section>
- [ Required ] I think it would be better if the design of the `footer` section on your design matches the design on Behance.net. Currently, your design differs from the design on Behance in the following ways.
  
  - [ ] The logo in the Behance design is aligned to the `left` while on your design the logo is centered.
  - [ ] The text in the Behance design is aligned to the `right` while on your design the text is centered.
  - [ ] The background color of the `footer` section on Behance.net is `#d3d3d3` while the background color on your design is `#ffffff`

- [ Required ] I think it would be better if you use the semantic `footer` tag as the container `tag` for this part of your webpage. HTML5 has the semantic `footer` tag which can be used to markup the footer section of a webpage, this improves the accessibility of your webpage to users using web accessibility tools like screen readers.

## Behance design
![Screenshot from 2023-07-05 23-10-21](https://github.com/anyars-encarta/First-Capstone/assets/16392046/370d70d2-1830-459b-a423-a29a08b984e8)

## Your design
![Screenshot from 2023-07-05 23-20-03](https://github.com/anyars-encarta/First-Capstone/assets/16392046/8f357bf7-222f-4e6d-8f4d-fd5deda09a53)

2023-07-05 21:37 UTC, Felix45 commented on about.html
> +        </section>
- [ Required ] I think it would be better if the design of the `footer` section on your design matches the design on Behance.net. Currently, your design differs from the design on Behance in the following ways.
  
  - [ ] The logo in the Behance design is aligned to the `left` while on your design the logo is centered.
  - [ ] The text in the Behance design is aligned to the `right` while on your design the text is centered.
  - [ ] The background color of the `footer` section on Behance.net is `#272A31` while the background color on your design is `#414246`

- [ Required ] I think it would be better if you use the semantic `footer` tag as the container `tag` for this part of your webpage. HTML5 has the semantic `footer` tag which can be used to markup the footer section of a webpage, this improves the accessibility of your webpage to users using web accessibility tools like screen readers.

## Behance design
![Screenshot from 2023-07-05 23-32-30](https://github.com/anyars-encarta/First-Capstone/assets/16392046/4f93e974-5e8b-45bf-a699-ad6df0c08cc6)


## Your design
![Screenshot from 2023-07-05 23-17-29](https://github.com/anyars-encarta/First-Capstone/assets/16392046/e6af8238-2bf0-4582-b4e2-9fb56172bff6)

2023-07-05 21:37 UTC, Felix45 commented on about.html
> +        </section>
- [ Required ] I think it would be better if your design looks almost identical to the original design, outside the content differences. If you have a look at the Behance design you'll notice that your design differs slightly in the following ways.
  
  - [ ] The horizontal divider between the two sections is missing from your design yet it's present in the Behance design.
  - [ ] The `logo` in the top section of your design has no border color, yet on the Behance design it has a border of color `#d3d3d3`
  - [ ] The vertical white space e.g. `margin` in your design is big compared to the same margin on the Behance design. Please see the screenshots below and rectify this.

## Your design
![Screenshot from 2023-07-05 23-50-43](https://github.com/anyars-encarta/First-Capstone/assets/16392046/4b7b753d-2b7e-42f2-90a6-604e603bd718)


## Behance design
![Screenshot from 2023-07-05 23-49-13](https://github.com/anyars-encarta/First-Capstone/assets/16392046/092a1516-5bd2-417a-aa37-dc23ea9685ac)

2023-07-05 21:37 UTC, Felix45 commented on index.html
> +            </div>
- [ Required ] Good job designing the top bar section of this webpage, however, I think you can still improve it by tweaking a few parts of the design to make it much better. Currently, it differs from the design on Behance in the following ways.
  
  - [ ] The background color of the topbar section in your design is `#3e3e3e`, yet on the Behance design it is `#272A31`
  - [ ] The social media links in the topbar section of the Behance design are aligned to the `right` of the topbar section and appear to be on the same edge as the button on the navigation menu. Please see the screenshot below for more details on this and rectify it.

## Your design
![Screenshot from 2023-07-06 00-02-40](https://github.com/anyars-encarta/First-Capstone/assets/16392046/c9bf9a20-d47d-49d5-bd17-488dfcf945ce)

## Behance design
![Screenshot from 2023-07-06 00-13-19](https://github.com/anyars-encarta/First-Capstone/assets/16392046/ab2db1df-13fc-4ce5-80b2-6264164c5461)

2023-07-05 21:37 UTC, Felix45 commented on style.css
> +  margin-left: -510px;
- [ Required ] I think it would be better if you ensure that the mobile navigation menu works as expected, currently, when I open the webpage in mobile view the hamburger menu is not visible. I think this is because of the `margin-left: -510px` applied on the `.hamburger` class. Please see the sample code below and rectify this for both the Home page and the About page.

```CSS
.hamburger {
    display: block;
    float: left;
    margin: 20px 0 0 20px;
}
```

| margin-left: -510px | float: left |
|-------------------------|------------------------|
|![Screenshot from 2023-07-06 00-16-17](https://github.com/anyars-encarta/First-Capstone/assets/16392046/81851128-4435-4a25-b2b6-e691c6de8aa9) | ![Screenshot from 2023-07-06 00-25-28](https://github.com/anyars-encarta/First-Capstone/assets/16392046/f54975d2-5481-4380-a3e8-ee3d4aea84ae) |

2023-07-06 13:05 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @anyars-encarta 

Good job so far! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the design
- ✅ Great job with CSS
- ✅ Descriptive PR and README file
- ✅ Correct Linters

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 13:05 UTC, KanzaTahreem commented on about.css
> +  }
- [ ] Good job for adding the divider and border for the image 🥇 However, please make sure that it looks almost identical to the given [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) ✨Kindly consider fixing the following 👇
- The border is covering the whole width of the page, but in the design guidelines it is different
- The divider is not covering the whole width of the page in your design, however, in the design guidelines it spans across the whole page with color `#d3d3d3`.
- Also, please reduce the vertical white/margin between the divider and past summit info 

_Kindly implement this for both versions_

Your design | Given design
---| ---|
![image](https://github.com/anyars-encarta/First-Capstone/assets/106119105/cfaef446-0d0d-43c9-992c-42c285d8a194) | ![image](https://github.com/anyars-encarta/First-Capstone/assets/106119105/f02fbbf9-2b52-4c8b-a7c3-23948ca28527)

2023-07-06 14:02 UTC, joel-kalema approved these changes
Hi @anyars-encarta 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 14:02 UTC, joel-kalema commented on index.html
> +            </div>
- [ ] [OPTIONAL] Good job @anyars-encarta , however, I'll suggest you to stick the design as much as possible  👍 

#### Original design

![Screenshot 2023-07-06 160046](https://github.com/anyars-encarta/First-Capstone/assets/57408419/87365424-9888-405d-9778-4db19a2739a3)

#### Your design

![Screenshot 2023-07-06 160011](https://github.com/anyars-encarta/First-Capstone/assets/57408419/af2b8891-a03e-47b7-b175-6d2dab3188b5)

2023-07-06 14:08 UTC, anyars-encarta commented on index.html
> +            </div>
Noted

2023-07-06 19:34 UTC, anyars-encarta commented on index.html
> +            </div>
I have effected your recommendation
![Effected](https://github.com/anyars-encarta/First-Capstone/assets/29536724/af846931-7488-4130-b769-568e7d374137)

2023-07-06 19:42 UTC, merged